#!/bin/bash

. ./functions_library.sh || { echo "Failed to source functions_library"; exit 1; }

<< INFO
Title: Automated Log Cleanup
Version 1.0
Author: Weronika Stępień
Purpose: Automatically purges old log files from specified directories
Features:
	* Automated 'log' file detection
	* Detailed feedback
	* Validation and error handling

Description:
	The script provides an efficient solution for managing and cleaning up log files generated by applications.
	Designed to support system performance and save disk space, this script automates the process
	of identifying and deleting log files that are older than one month.
	User provides a path to a specified directory in which the program is going to search for '.log' files.
	Before any change is made the user has to confirm their choice.


INFO

######################### MAIN CODE LOGIC #############################################################################################

#
# Clearing the screen for better readability
#

clear

#
# SEtting welcome page
#

terminal_stars
center_text "| LOGS DELETION |"
terminal_stars
echo

#
# Prompting the user about target directory
#

read -p "What is the path of the directory you want to search in -> " path

echo
center_text "SEARCHING...."
sleep 1

#
# Searching for files 'older than 30 days' and have ".log" extension using 'find' and '-mtime' command
#

files=$(find "$path" -name "*.log" -mtime +30)

#
# Check if any files were found
#

if [[ -z "$files" ]]
then
	echo

    	center_text "NO FILES THAT MATCH THE CRITERIA WERE FOUND"

	exit 0
else
	center_text "FILES FOUND...."

	echo

	sleep 0.75

	echo "Do you really want to delete below files?"
	echo
	echo "$files"
	echo

	if YesNo
	then

		# Deleting the found files
		echo "$files" | xargs rm -f


		# Infroming user about the results
		if [[ $? -eq 0 ]]
		then
			sleep 0.75

			center_text "SUCCESSFULLY DELETED"

			echo
		else
			echo

			center_text "ERROR"
			center_text "PROGRAM RUN INTO SOME ISSUES WHILE RUNNING"
			center_text "NO CHANGES WERE MADE"

			echo
		fi
	else
		center_text "NO CHANGES WERE MADE"

		echo
	fi
fi

